# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guanyin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '主机组'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': '用户组'},
        ),
        migrations.AlterField(
            model_name='host',
            name='host_key_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='name',
            field=models.CharField(max_length=128, verbose_name='主机组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
