# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guanyin', '0003_auto_20161107_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 11, 7, 9, 42, 13, 410842, tzinfo=utc), max_length=32, unique=True, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='hosts',
            field=models.ManyToManyField(blank=True, null=True, to='guanyin.Host', verbose_name='我的主机'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guanyin.UserGroup', verbose_name='属组'),
        ),
    ]
