# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guanyin', '0004_auto_20161107_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_path',
            field=models.CharField(default=datetime.datetime(2016, 11, 7, 9, 45, 47, 658760, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
