# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guanyin', '0005_user_avatar_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='头像路径'),
        ),
    ]
