# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guanyin', '0006_auto_20161107_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guanyin.User')),
            ],
            options={
                'verbose_name': '操作日志',
            },
        ),
    ]
