# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chouti_like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
