# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chouti_like', '0002_userinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chouti_like.UserType'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hobby',
            field=models.ManyToManyField(blank=True, null=True, to='chouti_like.Hobby'),
        ),
    ]
